project:
  type: website

website:
  title: "Michael's DS Hub"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: cville_rag.qmd
        text: Charlottesville RAG Assistant

format:
  html:
    theme:
      - light: cosmo
      - dark: darkly
    css: styles.css
    toc: true



